spring:
  application:
    name: eureka-server
server:
  port: 7002
eureka:
  instance:
    hostname: server2
  client:
    service-url:
      defaultZone: http://server1:7001/eureka/,http://server3:7003/eureka/
